### ISSUE TITLE
How to Run This Emulator?

### ISSUE THREAD

**Issue by WinPad1993** [azya52/Emulator2000#1]
I downloaded all this files in the repository.But,I cannot run them.So,I want to know how I can run this emulator.That means,I want know if I need any other package for python.And,what version of python do I need?(Tip:My python is Python 3.12).Moreover,which .py file should I run?
Please answer me.Thank you very much.

**Comment by azya52** [comment]
Sorry, didn't have time to answer. Did everything work out?

**Comment by WinPad1993** [comment]
The emulator worked out perfect.
I'm wrong,I shouldn't use the newest version of python.
Pyqt6 is only for Python 3.9 now.
And,thank you so much for getting back to me. 🙂






                       
原始邮件
                       
                     

发件人："azya52"< ***@***.*** &gt;;

发件时间：2024/1/20 20:29

收件人："azya52/Emulator2000"< ***@***.*** &gt;;

抄送人："MystemOS"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

主题：Re: [azya52/Emulator2000] How to Run This Emulator? (Issue #1)




 
Sorry, didn't have time to answer. Did everything work out?
